{"name": "test_Get_target_device_info", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'res.json'", "trace": "self = <Testcase_Devices.test_04_Get_target_device_info.Test_04_Get_target_device_info object at 0x0000017C2005E580>\n\n    @allure.feature('【需求点】：获取固定SN设备的信息')\n    @allure.story('【正常获取】')\n    @allure.severity('normal')\n    def test_Get_target_device_info(self):\n        ip = ReadIP().Read()\n        urls = ReadURL().Read()\n        device_sn = ReadSN().Read()\n        url1 = urls['url04']['url']\n        url = ip + url1\n        url = url.replace('sn',device_sn)\n        auth = ReadAuthorization().Read()\n        headers = {\n            'Authorization': auth,\n        }\n        method = 'get'\n        # 发送请求\n>       res = RequestTools().send_requests(method=method,url=url,header=headers)\n\ntest_04_Get_target_device_info.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <common.request_utill.RequestTools object at 0x0000017C203E9280>\nmethod = 'get'\nurl = 'http://10.10.10.137:80/deviceService/v1/devices/0000306E77162578?withStatus=true'\ndata = None\nheader = {'Authorization': 'Basic dXZsaWdodDp1dmxpZ2h0LXNlcnZlci1nM2E0QGlqaw=='}\n\n    def send_requests(self,method,url,data=None,header=None):\n          if method == 'get' or method == 'GET':\n             res = self.get_method(url,data,header)\n          elif method == 'post' or method =='POST':\n             res = self.post_method(url,data,header)\n          elif method == 'patch' or method == 'PATCH':\n             res = self.patch_method(url, data, header)\n          elif method == 'delete' or method == 'DELETE':\n             res = self.delete_method(url,data,header)\n          elif method == 'put' or method == 'PUT':\n             res = self.put_method(url,data,header)\n          else:\n             res = \"请求方式有误！\"\n          # res = json.dumps(res)\n          # res = json.loads(str(res).replace(\"'\", \"\\\"\"))\n          # res = json.loads(res)\n    \n>         with open('res.json','r') as fr:\nE         FileNotFoundError: [Errno 2] No such file or directory: 'res.json'\n\n..\\common\\request_utill.py:73: FileNotFoundError"}, "start": 1671585644245, "stop": 1671585644268, "uuid": "5c6414ac-cf31-4501-8e6e-b07182f00335", "historyId": "41c9e7470f0ec327a6f02ec3be0974e5", "testCaseId": "497176acc6aa09da0bda66145c2df40c", "fullName": "Testcase_Devices.test_04_Get_target_device_info.Test_04_Get_target_device_info#test_Get_target_device_info", "labels": [{"name": "story", "value": "【正常获取】"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "【需求点】：获取固定SN设备的信息"}, {"name": "parentSuite", "value": "Testcase_Devices"}, {"name": "suite", "value": "test_04_Get_target_device_info"}, {"name": "subSuite", "value": "Test_04_Get_target_device_info"}, {"name": "host", "value": "SIE180286"}, {"name": "thread", "value": "5668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Devices.test_04_Get_target_device_info"}]}